// DO NOT EDIT. This file is generated by Fresh.
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/api/users.ts";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: { "./routes/index.tsx": $0, "./routes/api/users.ts": $1 },
  islands: { "./islands/Counter.tsx": $$0 },
  baseUrl: import.meta.url,
};

export default manifest;
