/**
 * Gotchas Analyzer
 *
 * Identifies auto-generated directories, files Claude shouldn't modify,
 * and common project-specific pitfalls.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { StackProfile } from "./stack-detector.js";

export interface Gotcha {
  rule: string; // "DON'T modify X", "ALWAYS do Y"
  reason: string;
  severity: "critical" | "important" | "nice-to-have";
}

export interface GotchasProfile {
  generatedDirs: string[];
  generatedFiles: string[];
  gotchas: Gotcha[];
}

export async function analyzeGotchas(
  rootDir: string,
  stack: StackProfile
): Promise<GotchasProfile> {
  const generatedDirs: string[] = [];
  const generatedFiles: string[] = [];
  const gotchas: Gotcha[] = [];

  // ── Parse .gitignore for generated paths ──
  const gitignore = readSafe(join(rootDir, ".gitignore"));
  if (gitignore) {
    const patterns = gitignore
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#"));

    // Common generated directory patterns
    const genPatterns = [
      /^(dist|build|out|\.next|\.nuxt)\/?$/,
      /generated/i,
      /^(coverage|\.coverage)\/?$/,
      /^(tmp|temp|log|logs)\/?$/,
      /assets\/builds/,
    ];

    for (const pattern of patterns) {
      if (genPatterns.some((gp) => gp.test(pattern))) {
        if (pattern.endsWith("/")) generatedDirs.push(pattern);
        else generatedDirs.push(pattern);
      }
    }
  }

  // ── Framework-specific gotchas ──
  if (stack.framework === "rails") {
    generatedFiles.push("db/schema.rb");
    gotchas.push(
      {
        rule: "DON'T modify db/schema.rb directly",
        reason: "Use migrations only — schema.rb is auto-generated",
        severity: "critical",
      },
      {
        rule: "DON'T skip Pundit authorization in controllers",
        reason: "Every controller action needs `authorize @resource`",
        severity: "critical",
      },
      {
        rule: "DON'T add N+1 queries",
        reason: "Use `.includes()` or `.preload()` for associations",
        severity: "important",
      },
      {
        rule: "DON'T put business logic in controllers",
        reason: "Extract to service objects in app/services/",
        severity: "important",
      },
      {
        rule: "DON'T commit credentials directly",
        reason: "Use `bin/rails credentials:edit` for secrets",
        severity: "critical",
      },
    );

    if (stack.keyDeps["cssbundling-rails"]) {
      generatedDirs.push("app/assets/builds/");
      gotchas.push({
        rule: "DON'T modify app/assets/builds/",
        reason: "Auto-generated by cssbundling-rails",
        severity: "important",
      });
    }
  }

  if (stack.framework === "nextjs") {
    generatedDirs.push(".next/");
    gotchas.push({
      rule: "DON'T modify .next/ directory",
      reason: "Auto-generated build cache",
      severity: "critical",
    });
  }

  // ── Django ──
  if (stack.framework === "django") {
    gotchas.push(
      {
        rule: "DON'T modify migration files after they're applied",
        reason: "Create new migrations instead — editing applied migrations breaks the chain",
        severity: "critical",
      },
      {
        rule: "DON'T hardcode settings values",
        reason: "Use environment variables via django-environ or os.environ",
        severity: "important",
      },
      {
        rule: "DON'T use raw SQL without parameterization",
        reason: "Use Django ORM or parameterized queries to prevent SQL injection",
        severity: "critical",
      },
      {
        rule: "DON'T put business logic in views",
        reason: "Extract to services or model methods — views are for HTTP handling",
        severity: "important",
      },
    );
  }

  // ── FastAPI ──
  if (stack.framework === "fastapi") {
    gotchas.push(
      {
        rule: "DON'T block the event loop with sync operations",
        reason: "Use async/await for I/O — blocking calls freeze the entire server",
        severity: "critical",
      },
      {
        rule: "ALWAYS use Pydantic models for request/response validation",
        reason: "Type safety and auto-documentation via OpenAPI",
        severity: "important",
      },
      {
        rule: "DON'T create DB sessions outside of dependency injection",
        reason: "Use FastAPI's Depends() for proper session lifecycle",
        severity: "important",
      },
    );
  }

  // ── Laravel ──
  if (stack.framework === "laravel") {
    gotchas.push(
      {
        rule: "DON'T modify migration files after they run",
        reason: "Create new migrations — editing old ones causes state mismatch",
        severity: "critical",
      },
      {
        rule: "DON'T put business logic in controllers",
        reason: "Use service classes or actions — controllers are thin",
        severity: "important",
      },
      {
        rule: "DON'T skip Form Request validation",
        reason: "Always validate via Form Request classes, not inline in controllers",
        severity: "important",
      },
      {
        rule: "DON'T use env() outside config files",
        reason: "Cache breaks env() calls — use config() with config files that read env()",
        severity: "critical",
      },
    );
    generatedDirs.push("storage/", "bootstrap/cache/");
  }

  // ── Phoenix ──
  if (stack.framework === "phoenix") {
    gotchas.push(
      {
        rule: "DON'T modify Ecto migrations after they're run",
        reason: "Roll back first or create new migrations",
        severity: "critical",
      },
      {
        rule: "ALWAYS use changesets for data validation",
        reason: "Ecto changesets are the canonical validation layer",
        severity: "important",
      },
      {
        rule: "DON'T leak PubSub topics between contexts",
        reason: "Keep context boundaries clean for maintainability",
        severity: "important",
      },
    );
  }

  // ── Go ──
  if (stack.language === "go") {
    gotchas.push(
      {
        rule: "DON'T ignore errors — always check returned error values",
        reason: "Go uses explicit error handling; unchecked errors cause silent failures",
        severity: "critical",
      },
      {
        rule: "DON'T use global state for request-scoped data",
        reason: "Use context.Context for request-scoped values",
        severity: "important",
      },
    );
    if (existsSync(join(rootDir, "go.sum"))) {
      generatedFiles.push("go.sum");
      gotchas.push({
        rule: "DON'T manually edit go.sum",
        reason: "Auto-generated by go mod tidy — commit it but don't modify by hand",
        severity: "important",
      });
    }
  }

  // ── Rust ──
  if (stack.language === "rust") {
    gotchas.push(
      {
        rule: "DON'T use .unwrap() in production code",
        reason: "Use proper error handling with ? operator or match",
        severity: "critical",
      },
      {
        rule: "DON'T fight the borrow checker — restructure code instead",
        reason: "If you need multiple mutable references, consider Arc<Mutex<T>> or restructure",
        severity: "important",
      },
    );
    if (existsSync(join(rootDir, "Cargo.lock"))) {
      generatedFiles.push("Cargo.lock");
    }
  }

  // ── Spring Boot ──
  if (stack.framework === "spring") {
    gotchas.push(
      {
        rule: "DON'T put business logic in controllers",
        reason: "Use @Service classes — controllers call services, services call repositories",
        severity: "important",
      },
      {
        rule: "DON'T skip @Transactional on service methods that write",
        reason: "Database operations need proper transaction boundaries",
        severity: "critical",
      },
      {
        rule: "DON'T hardcode config values",
        reason: "Use @Value or @ConfigurationProperties with application.properties",
        severity: "important",
      },
    );
  }

  // Prisma
  if (stack.keyDeps["@prisma/client"]) {
    generatedDirs.push("node_modules/.prisma/");
    gotchas.push(
      {
        rule: "DON'T modify files in node_modules/.prisma/",
        reason: "Auto-generated by `prisma generate`",
        severity: "critical",
      },
      {
        rule: "ALWAYS run `npx prisma generate` after schema changes",
        reason: "Client needs regeneration to reflect schema updates",
        severity: "important",
      },
    );
  }

  // Generic .env gotcha
  if (existsSync(join(rootDir, ".env.example")) || existsSync(join(rootDir, ".env"))) {
    gotchas.push({
      rule: "DON'T commit .env files",
      reason: "Use .env.example for template, actual env vars should be secrets",
      severity: "critical",
    });
  }

  return { generatedDirs, generatedFiles, gotchas };
}

function readSafe(path: string): string | null {
  try {
    return existsSync(path) ? readFileSync(path, "utf-8") : null;
  } catch {
    return null;
  }
}
