/**
 * Gotchas Analyzer
 *
 * Identifies auto-generated directories, files Claude shouldn't modify,
 * and common project-specific pitfalls.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { StackProfile } from "./stack-detector.js";

export interface Gotcha {
  rule: string; // "DON'T modify X", "ALWAYS do Y"
  reason: string;
  severity: "critical" | "important" | "nice-to-have";
}

export interface GotchasProfile {
  generatedDirs: string[];
  generatedFiles: string[];
  gotchas: Gotcha[];
}

export async function analyzeGotchas(
  rootDir: string,
  stack: StackProfile
): Promise<GotchasProfile> {
  const generatedDirs: string[] = [];
  const generatedFiles: string[] = [];
  const gotchas: Gotcha[] = [];

  // ── Parse .gitignore for generated paths ──
  const gitignore = readSafe(join(rootDir, ".gitignore"));
  if (gitignore) {
    const patterns = gitignore
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("#"));

    // Common generated directory patterns
    const genPatterns = [
      /^(dist|build|out|\.next|\.nuxt)\/?$/,
      /generated/i,
      /^(coverage|\.coverage)\/?$/,
      /^(tmp|temp|log|logs)\/?$/,
      /assets\/builds/,
    ];

    for (const pattern of patterns) {
      if (genPatterns.some((gp) => gp.test(pattern))) {
        if (pattern.endsWith("/")) generatedDirs.push(pattern);
        else generatedDirs.push(pattern);
      }
    }
  }

  // ── Framework-specific gotchas ──
  if (stack.framework === "rails") {
    generatedFiles.push("db/schema.rb");
    gotchas.push(
      {
        rule: "DON'T modify db/schema.rb directly",
        reason: "Use migrations only — schema.rb is auto-generated",
        severity: "critical",
      },
      {
        rule: "DON'T skip Pundit authorization in controllers",
        reason: "Every controller action needs `authorize @resource`",
        severity: "critical",
      },
      {
        rule: "DON'T add N+1 queries",
        reason: "Use `.includes()` or `.preload()` for associations",
        severity: "important",
      },
      {
        rule: "DON'T put business logic in controllers",
        reason: "Extract to service objects in app/services/",
        severity: "important",
      },
      {
        rule: "DON'T commit credentials directly",
        reason: "Use `bin/rails credentials:edit` for secrets",
        severity: "critical",
      },
    );

    if (stack.keyDeps["cssbundling-rails"]) {
      generatedDirs.push("app/assets/builds/");
      gotchas.push({
        rule: "DON'T modify app/assets/builds/",
        reason: "Auto-generated by cssbundling-rails",
        severity: "important",
      });
    }
  }

  if (stack.framework === "nextjs") {
    generatedDirs.push(".next/");
    gotchas.push({
      rule: "DON'T modify .next/ directory",
      reason: "Auto-generated build cache",
      severity: "critical",
    });
  }

  // ── Django ──
  if (stack.framework === "django") {
    gotchas.push(
      {
        rule: "DON'T modify migration files after they're applied",
        reason: "Create new migrations instead — editing applied migrations breaks the chain",
        severity: "critical",
      },
      {
        rule: "DON'T hardcode settings values",
        reason: "Use environment variables via django-environ or os.environ",
        severity: "important",
      },
      {
        rule: "DON'T use raw SQL without parameterization",
        reason: "Use Django ORM or parameterized queries to prevent SQL injection",
        severity: "critical",
      },
      {
        rule: "DON'T put business logic in views",
        reason: "Extract to services or model methods — views are for HTTP handling",
        severity: "important",
      },
    );
  }

  // ── FastAPI ──
  if (stack.framework === "fastapi") {
    gotchas.push(
      {
        rule: "DON'T block the event loop with sync operations",
        reason: "Use async/await for I/O — blocking calls freeze the entire server",
        severity: "critical",
      },
      {
        rule: "ALWAYS use Pydantic models for request/response validation",
        reason: "Type safety and auto-documentation via OpenAPI",
        severity: "important",
      },
      {
        rule: "DON'T create DB sessions outside of dependency injection",
        reason: "Use FastAPI's Depends() for proper session lifecycle",
        severity: "important",
      },
    );
  }

  // ── Laravel ──
  if (stack.framework === "laravel") {
    gotchas.push(
      {
        rule: "DON'T modify migration files after they run",
        reason: "Create new migrations — editing old ones causes state mismatch",
        severity: "critical",
      },
      {
        rule: "DON'T put business logic in controllers",
        reason: "Use service classes or actions — controllers are thin",
        severity: "important",
      },
      {
        rule: "DON'T skip Form Request validation",
        reason: "Always validate via Form Request classes, not inline in controllers",
        severity: "important",
      },
      {
        rule: "DON'T use env() outside config files",
        reason: "Cache breaks env() calls — use config() with config files that read env()",
        severity: "critical",
      },
    );
    generatedDirs.push("storage/", "bootstrap/cache/");
  }

  // ── Phoenix ──
  if (stack.framework === "phoenix") {
    gotchas.push(
      {
        rule: "DON'T modify Ecto migrations after they're run",
        reason: "Roll back first or create new migrations",
        severity: "critical",
      },
      {
        rule: "ALWAYS use changesets for data validation",
        reason: "Ecto changesets are the canonical validation layer",
        severity: "important",
      },
      {
        rule: "DON'T leak PubSub topics between contexts",
        reason: "Keep context boundaries clean for maintainability",
        severity: "important",
      },
    );
  }

  // ── Go ──
  if (stack.language === "go") {
    gotchas.push(
      {
        rule: "DON'T ignore errors — always check returned error values",
        reason: "Go uses explicit error handling; unchecked errors cause silent failures",
        severity: "critical",
      },
      {
        rule: "DON'T use global state for request-scoped data",
        reason: "Use context.Context for request-scoped values",
        severity: "important",
      },
    );
    if (existsSync(join(rootDir, "go.sum"))) {
      generatedFiles.push("go.sum");
      gotchas.push({
        rule: "DON'T manually edit go.sum",
        reason: "Auto-generated by go mod tidy — commit it but don't modify by hand",
        severity: "important",
      });
    }
  }

  // ── Rust ──
  if (stack.language === "rust") {
    gotchas.push(
      {
        rule: "DON'T use .unwrap() in production code",
        reason: "Use proper error handling with ? operator or match",
        severity: "critical",
      },
      {
        rule: "DON'T fight the borrow checker — restructure code instead",
        reason: "If you need multiple mutable references, consider Arc<Mutex<T>> or restructure",
        severity: "important",
      },
    );
    if (existsSync(join(rootDir, "Cargo.lock"))) {
      generatedFiles.push("Cargo.lock");
    }
  }

  // ── Spring Boot ──
  if (stack.framework === "spring") {
    gotchas.push(
      {
        rule: "DON'T put business logic in controllers",
        reason: "Use @Service classes — controllers call services, services call repositories",
        severity: "important",
      },
      {
        rule: "DON'T skip @Transactional on service methods that write",
        reason: "Database operations need proper transaction boundaries",
        severity: "critical",
      },
      {
        rule: "DON'T hardcode config values",
        reason: "Use @Value or @ConfigurationProperties with application.properties",
        severity: "important",
      },
    );
  }

  // ── C# / .NET ──
  if (stack.language === "csharp") {
    gotchas.push(
      {
        rule: "DON'T use async void — use async Task",
        reason: "async void swallows exceptions and breaks error handling",
        severity: "critical",
      },
      {
        rule: "DON'T instantiate HttpClient directly — use IHttpClientFactory",
        reason: "Direct HttpClient causes socket exhaustion under load",
        severity: "critical",
      },
      {
        rule: "ALWAYS use dependency injection for services",
        reason: "ASP.NET Core DI container is the standard — avoid static service locators",
        severity: "important",
      },
      {
        rule: "DON'T use Console.WriteLine for logging — use ILogger<T>",
        reason: "ILogger integrates with structured logging and log providers",
        severity: "important",
      },
    );
  }

  // ── Kotlin ──
  if (stack.language === "kotlin") {
    gotchas.push(
      {
        rule: "DON'T use !! (non-null assertion) — handle nulls properly",
        reason: "!! throws NullPointerException — use ?. or ?: or let {}",
        severity: "critical",
      },
      {
        rule: "ALWAYS use data class for DTOs and value objects",
        reason: "data class gives equals, hashCode, copy, toString for free",
        severity: "important",
      },
      {
        rule: "DON'T use threads directly — use coroutines",
        reason: "Kotlin coroutines are lighter weight and compose better than threads",
        severity: "important",
      },
      {
        rule: "ALWAYS prefer sealed class/interface for state modeling",
        reason: "Sealed types enable exhaustive when expressions",
        severity: "nice-to-have",
      },
    );
  }

  // ── Dart / Flutter ──
  if (stack.language === "dart") {
    gotchas.push(
      {
        rule: "ALWAYS use const constructors where possible",
        reason: "const widgets are cached and skip rebuilds — huge performance win",
        severity: "critical",
      },
      {
        rule: "DON'T call setState after dispose",
        reason: "Causes 'setState() called after dispose()' error — check mounted",
        severity: "critical",
      },
      {
        rule: "ALWAYS use key parameter in list item widgets",
        reason: "Without keys, Flutter can't diff list items efficiently",
        severity: "important",
      },
      {
        rule: "DON'T use dynamic type — prefer explicit types",
        reason: "dynamic bypasses type safety and causes runtime errors",
        severity: "important",
      },
    );
    generatedDirs.push(".dart_tool/", "build/");
  }

  // ── Swift / Vapor ──
  if (stack.language === "swift") {
    gotchas.push(
      {
        rule: "DON'T force unwrap with ! — use if let or guard let",
        reason: "Force unwrapping crashes at runtime on nil values",
        severity: "critical",
      },
      {
        rule: "ALWAYS use async/await — not completion handlers",
        reason: "Modern Swift concurrency is safer and more readable",
        severity: "important",
      },
      {
        rule: "ALWAYS use Content protocol for JSON codable types",
        reason: "Vapor's Content protocol handles encoding/decoding automatically",
        severity: "important",
      },
    );
    generatedDirs.push(".build/");
  }

  // ── Generic TypeScript fallback ──
  if (stack.language === "typescript" && gotchas.length === 0) {
    gotchas.push(
      {
        rule: "DON'T use `any` — prefer `unknown` with type narrowing",
        reason: "`any` disables type checking and defeats the purpose of TypeScript",
        severity: "important",
      },
      {
        rule: "ALWAYS use .js extension in ESM import paths",
        reason: "TypeScript requires .js extensions in output-relative imports for ESM",
        severity: "important",
      },
    );
    // Check tsconfig for strict mode
    const tsconfig = readSafe(join(rootDir, "tsconfig.json"));
    if (tsconfig && !tsconfig.includes('"strict"')) {
      gotchas.push({
        rule: "ALWAYS enable strict mode in tsconfig.json",
        reason: "Non-strict mode allows implicit any and null issues to slip through",
        severity: "nice-to-have",
      });
    }
  }

  // ── Generic JavaScript fallback ──
  if (stack.language === "javascript" && gotchas.length === 0) {
    gotchas.push({
      rule: "ALWAYS use strict mode or ESM modules",
      reason: "Strict mode catches common bugs like implicit globals and silent errors",
      severity: "important",
    });
  }

  // Prisma
  if (stack.keyDeps["@prisma/client"]) {
    generatedDirs.push("node_modules/.prisma/");
    gotchas.push(
      {
        rule: "DON'T modify files in node_modules/.prisma/",
        reason: "Auto-generated by `prisma generate`",
        severity: "critical",
      },
      {
        rule: "ALWAYS run `npx prisma generate` after schema changes",
        reason: "Client needs regeneration to reflect schema updates",
        severity: "important",
      },
    );
  }

  // Generic .env gotcha
  if (existsSync(join(rootDir, ".env.example")) || existsSync(join(rootDir, ".env"))) {
    gotchas.push({
      rule: "DON'T commit .env files",
      reason: "Use .env.example for template, actual env vars should be secrets",
      severity: "critical",
    });
  }

  return { generatedDirs, generatedFiles, gotchas };
}

function readSafe(path: string): string | null {
  try {
    return existsSync(path) ? readFileSync(path, "utf-8") : null;
  } catch {
    return null;
  }
}
