source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"

# Frontend
gem "turbo-rails"
gem "stimulus-rails"
gem "importmap-rails"
gem "tailwindcss-rails"

# Auth & Authorization
gem "devise"
gem "pundit"

# Background Jobs
gem "sidekiq", "~> 7.0"

# Pagination
gem "pagy", "~> 9.0"

# Search
gem "pg_search"

group :development, :test do
  gem "debug"
  gem "factory_bot_rails"
  gem "rspec-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers"
  gem "simplecov", require: false
  gem "webmock"
  gem "vcr"
end
