import type { LintPreset } from "../types.js";

export const defaultPreset: LintPreset = {
  name: "default",
  description: "Balanced preset for most projects",
  rules: [
    "token-budget",
    "token-bloat",
    "missing-verify",
    "stale-ref",
    "style-vs-linter",
    "vague",
    "redundant",
    "no-architecture",
    "missing-gotchas",
    "no-imports",
    "missing-patterns",
    "import-candidate",
    "context-efficiency",
    "duplicate-content",
    "commands-runnable",
    "framework-version-sync",
    "depth-imbalance",
    "contradictory-advice",
    "empty-section",
    "missing-testing",
    "missing-db-context",
    "inconsistent-pkg-manager",
    "broken-markdown",
    "missing-env-setup",
    "excessive-nesting",
    "unresolved-placeholders",
  ],
};
