import type { LintPreset } from "../types.js";

export const strictPreset: LintPreset = {
  name: "strict",
  description: "Maximum rigor — all suggestions promoted to warnings",
  rules: [
    "token-budget",
    "token-bloat",
    "missing-verify",
    "stale-ref",
    "style-vs-linter",
    "vague",
    "redundant",
    "no-architecture",
    "missing-gotchas",
    "no-imports",
    "missing-patterns",
    "import-candidate",
    "context-efficiency",
    "duplicate-content",
    "commands-runnable",
    "framework-version-sync",
    "depth-imbalance",
    "contradictory-advice",
    "empty-section",
    "missing-testing",
    "missing-db-context",
    "inconsistent-pkg-manager",
    "broken-markdown",
    "missing-env-setup",
    "excessive-nesting",
    "unresolved-placeholders",
  ],
  overrides: {
    "missing-gotchas": "warning",
    "no-imports": "warning",
    "missing-patterns": "warning",
    "import-candidate": "warning",
    "context-efficiency": "warning",
    "depth-imbalance": "warning",
    "missing-testing": "warning",
    "missing-db-context": "warning",
    "missing-env-setup": "warning",
    "excessive-nesting": "warning",
  },
};
